Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  # mongodb
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http      = "http://10.0.2.2:53128"
    config.proxy.https     = "http://10.0.2.2:53128"
    config.proxy.no_proxy  = "localhost,127.0.0.1,.detss.corpintra.net"
  end

  config.vm.provision "shell", inline: "(groupadd docker || true) && usermod -G docker vagrant"
  config.vm.provision "shell", inline: "cp /vagrant/vagrant/certificates/* /etc/pki/ca-trust/source/anchors/"
  config.vm.provision "shell", inline: "cp /vagrant/vagrant/repos/* /etc/yum.repos.d/"
  config.vm.provision "shell", inline: "yum install -y device-mapper-event-libs"
  config.vm.provision "shell", inline: "yum install -y rsync"
  config.vm.provision "shell", inline: "yum --enablerepo=virt7-testing install -y docker"
  config.vm.provision "shell", inline: "systemctl restart docker", run: "always"
  config.vm.provision "shell", inline: "update-ca-trust enable", run: "always"
  config.vm.provision "shell", inline: "sleep 5", run: "always"
end
